name: Deploy API

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # Explicitly using Node.js 20

      - name: Install dependencies
        run: |
          npm install

      - name: Install PM2
        run: |
          npm install -g pm2

      - name: Start SSH Agent and Add SSH Key
        id: ssh-agent-setup
        run: |
          eval "$(ssh-agent -s)"  # Start the SSH agent
          echo "$SSH_KEY" | tr -d '\r' | ssh-add -  # Add the SSH key
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}

      - name: Test SSH Connection
        env:
          VM_USER: ${{ secrets.VM_USER }}
          VM_HOST: ${{ secrets.VM_HOST }}
        run: |
          ssh -o StrictHostKeyChecking=no $VM_USER@$VM_HOST "echo 'SSH connection successful!'"

      - name: Deploy to VM
        if: success()  # Only run if SSH connection test was successful
        env:
          VM_USER: ${{ secrets.VM_USER }}
          VM_HOST: ${{ secrets.VM_HOST }}
        run: |
          ssh -o StrictHostKeyChecking=no $VM_USER@$VM_HOST "
            pm2 stop all || true
            pm2 start server.js --name 'backend-api'
          "

      - name: Check Deployment Status
        env:
          VM_USER: ${{ secrets.VM_USER }}
          VM_HOST: ${{ secrets.VM_HOST }}
        run: |
          ssh -o StrictHostKeyChecking=no $VM_USER@$VM_HOST "pm2 list"
